### ISSUE TITLE
About animation_lock and application_delay, is there any refer for these values?

### ISSUE THREAD

**Issue by IcyTide** [Amarantine-xiv/Amas-FF14-Combat-Sim_source#23]
As the title

**Comment by Amarantine-xiv** [comment]
Animation locks are generally assume if casted spells, or gotten from the Balance, I believe.

Application delays are here: https://docs.google.com/spreadsheets/d/1Emevsz5_oJdmkXy23hZQUXimirZQaoo5BejSzL3hZ9I/edit?gid=1868377879#gid=1868377879

**Comment by IcyTide** [comment]
Thanks, it definetly helps

**Comment by Amarantine-xiv** [comment]
No problem!
